/**
 * This is the abstract/generic interface for a "connection"
 * to a blob storage service, such as Amazon Web Services S3
 * Azure's "blob store", or a local (or network-mapped) file system.
 *
 * @module
 */

const fsAsync = require( "fs/promises" );

// TODO: make platform-agnostic, not tied to node,js
const { createReadStream, createWriteStream } = require( "node:fs" );
const { Readable, pipeline } = require( "node:stream" );
const { promisify } = require( "node:util" );

const core = require( "@toolbocks/core" );
const bufferUtils = require( "@toolbocks/buffer" );
const fileUtils = require( "@toolbocks/files" );
const jsonUtils = require( "@toolbocks/json" );

const { moduleUtils, constants, typeUtils, stringUtils, arrayUtils } = core;

const { _ud, _mt = "", _hyphen, _fun, $scope } = constants;

(function exposeModule()
{
    /**
     * Define a string key which is unlikely to collide with other libraries or properties.
     * We use this to store the module generated by this function in global scope.
     * We can avoid re-executing the rest of this function if the module is already defined.
     */
    const INTERNAL_NAME = "__BOCK__STORAGE_UTILS_BASE__";

    /**
     * Checks to see if this module is already defines and available in the global scope
     * Returns the existing module instead of recreating it, if it is already present.
     */
    if ( $scope() && (null != $scope()[INTERNAL_NAME]) )
    {
        return $scope()[INTERNAL_NAME];
    }

    const
        {
            ToolBocksModule,
            ModuleEvent,
            __Error,
            IllegalArgumentError,
            NotImplementedError,
            hasProperty,
            readProperty,
            attempt,
            attemptSilent,
            asyncAttempt,
            lock,
            $ln
        } = moduleUtils;

    const
        {
            isNull,
            isNonNullObject,
            isFunction,
            isString,
            isArray,
            isTypedArray,
            isClass,
            getClass,
            getClassName,
            isSubclassOf
        } = typeUtils;

    const { asString, asInt, _lct, isBlank } = stringUtils;

    const { asArray } = arrayUtils;

    const { join, normalize, resolvePath, relativePath, getDirectoryName, getTempDirectory } = fileUtils;

    const { asObject, asJson, parseJson } = jsonUtils;

    const BLOB_STORE_OPERATIONS =
        lock( {
                  READ: "read",
                  WRITE: "write"
              } );

    /**
     * Abstract base class for Blob Store Clients,
     * such as AWS S3, Azure Client, or the File System.
     *
     * @abstract
     * @class
     *
     */
    class BlobStorageClient extends EventTarget
    {
        constructor()
        {
            super();

            // prevent direct instantiation
            if ( new.target === BlobStorageClient )
            {
                throw new __Error( "Cannot instantiate abstract class BlobStorageClient directly. BlobStorageClient is intended to be subclassed" );
            }
        }

        async init( ...pArgs )
        {
            return this;
        }

        async dispose( ...pArgs )
        {
            return this;
        }

        async upload( pKey, pData, pOptions = {} )
        {
            throw new NotImplementedError( "Method 'upload()' must be implemented." );
        }

        async download( pKey, pOptions = {} )
        {
            throw new NotImplementedError( "Method 'download()' must be implemented." );
        }

        async delete( pKey )
        {
            throw new NotImplementedError( "Method 'delete()' must be implemented." );
        }

        async deleteMany( ...pKeys )
        {
            throw new NotImplementedError( "Method 'deleteMany()' must be implemented." );
        }

        async exists( pKey )
        {
            throw new NotImplementedError( "Method 'exists()' must be implemented." );
        }

        async getMetadata( pKey )
        {
            throw new NotImplementedError( "Method 'getMetadata()' must be implemented." );
        }

        async list( pPrefix = _mt, pOptions = {} )
        {
            throw new NotImplementedError( "Method 'list()' must be implemented." );
        }

        /**
         * Async generator that yields objects one by one across page boundaries.
         * @returns {AsyncGenerator<*>}
         * @param pPrefix
         * @param pOptions
         */
        async* listStream( pPrefix = "", pOptions = {} )
        {
            throw new NotImplementedError( "Method 'listStream()' must be implemented." );
        }

        async getPresignedUrl( pKey, pOperation = BLOB_STORE_OPERATIONS.READ, pOptions = {} )
        {
            throw new NotImplementedError( "Method 'getPresignedUrl()' must be implemented." );
        }

        async copy( sourceKey, destinationKey )
        {
            throw new NotImplementedError( "Method 'copy()' must be implemented." );
        }

        [Symbol.toStringTag]()
        {
            return `[object ${getClassName( this )}]`;
        }
    }


    const streamPipeline = promisify( pipeline );

    /**
     * A client for storing and managing file-based blobs in the local filesystem.
     * Extends the BlobStorageClient to provide local disk storage functionality.
     *
     * @class
     *
     * @see BlobStorageClient
     */
    class LocalDiskStorageClient extends BlobStorageClient
    {
        /**
         * Constructs an instance of LocalDiskStorageClient
         * and initializes it with the provided options.
         *
         * @param {Object} [pOptions={}] - The options used to configure the instance.
         * @param {string} [pOptions.rootFolder] - The root folder path for the instance. Defaults to a temporary directory.
         * @param {string} [pOptions.baseUrl] - The base URL for the instance. Defaults to a file URL based on the root folder.
         *
         * @constructor
         */
        constructor( pOptions = {} )
        {
            super( pOptions );

            const options = asObject( pOptions ?? {} );

            const root = asString( options.rootFolder || getTempDirectory(), true ) || getTempDirectory();

            this.rootFolder = resolvePath( root );

            this.baseUrl = options.baseUrl || asString( `file:///${this.rootFolder}/` ).replaceAll( /\/{4}/g, "///" );
        }

        /**
         * Returns the full path to the desired content,
         * safely preventing navigation outside the root folder.
         *
         * @throws IllegalArgumentError if the resolved path does not start with the root folder
         *
         * @param {string} pKey path/name to content
         *
         * @returns {string} the full path to the desired content
         */
        #resolvePath( pKey )
        {
            const key = asString( pKey, true );

            const safeKey = normalize( key ).replace( /^(\.\.[\/\\])+/, _mt );
            const fullPath = resolvePath( join( this.rootFolder, safeKey ) );

            if ( !fullPath.startsWith( this.rootFolder ) )
            {
                throw new IllegalArgumentError( "Directory traversal out of root folder is forbidden.", { detail: key }, key );
            }

            return fullPath;
        }

        /**
         * Returns the file path to the metadata for the file.
         * N.B. May not exist!
         *
         * @param pFilePath
         *
         * @returns {string}
         *
         * @private
         */
        #getMetadataPath( pFilePath )
        {
            const filePath = asString( pFilePath, true );
            return `${filePath}.meta.json`;
        }

        /**
         * Stores the provided data under the key specified.
         * That is, saves the bytes or string as a file.
         *
         * @param {string} pKey a path or name relative to the root folder at which to store the specified data
         *
         * @param {Buffer|TypedArray|String} pData the content to store
         *
         * @param {Object} [pOptions={}] (optional) an object specifying the encoding to use for string data
         *                               and/or metadata to store with the content.
         *
         * @returns {Promise<Object>} an object with the resolved key, filePath, ETag, and url of the stored data.
         */
        async upload( pKey, pData, pOptions = {} )
        {
            const key = asString( pKey, true );

            const options = asObject( pOptions ?? {} );

            const metadata = { ...(asObject( options.metadata ?? {} )) };

            metadata.contentType = readProperty( options, "content_type", "mime_type" ) ||
                                   readProperty( metadata, "content_type", "mime_type" ) ||
                                   "application/octet-stream";

            const encoding = asString( options.encoding || metadata.encoding || "utf-8", true ) || "utf-8";

            const filePath = this.#resolvePath( key );

            await fsAsync.mkdir( getDirectoryName( filePath ), { recursive: true } );

            if ( isTypedArray( pData ) || Buffer.isBuffer( pData ) )
            {
                await fsAsync.writeFile( filePath, (Buffer.isBuffer( pData ) ? pData : Buffer.from( pData?.buffer ?? pData )) );
            }
            else if ( isString( pData ) )
            {
                await fsAsync.writeFile( filePath, asString( pData ), encoding );
            }
            else if ( pData instanceof Readable || _fun === typeof pData[Symbol.asyncIterator] )
            {
                const writeStream = createWriteStream( filePath );

                await asyncAttempt( async() => await streamPipeline( pData, writeStream ) );

                await asyncAttempt( async() => writeStream.close() );
            }
            else
            {
                throw new IllegalArgumentError( "Unsupported data format for LocalDiskStorageClient upload.",
                                                {
                                                    detail: pData,
                                                    type: typeof pData
                                                }, pData );
            }

            await asyncAttempt( async() => await fsAsync.writeFile( this.#getMetadataPath( filePath ), asJson( metadata ?? options ) ) );

            const stats = await fsAsync.stat( filePath );

            if ( isNonNullObject( stats ) )
            {
                const obj =
                    {
                        key,
                        filePath,
                        etag: `"${stats.mtimeMs.toString( 16 )}-${stats.size.toString( 16 )}"`,
                        url: `${this.baseUrl}/${key}`,
                    };

                attempt( () => this.dispatchEvent( new ModuleEvent( "upload", { detail: obj }, { ...obj } ) ) );

                return lock( obj );
            }

            throw new __Error( `Failed to persist ${filePath}` );
        }

        /**
         * Returns a ReadStream of the bytes requested.
         *
         * @param {string} pKey file path or name, relative to the root folder
         *
         * @param {object} [pOptions={}] (optional) an object specifying the range of bytes to return
         *                               example: {start: 0, end: 4099}
         *
         * @returns {Promise<ReadStream>} a stream to consume
         */
        async download( pKey, pOptions = {} )
        {
            const key = asString( pKey, true );

            const options = asObject( pOptions ?? {} );

            const filePath = this.#resolvePath( key );

            const range = asString( readProperty( options, "range" ), true );

            if ( range && !isBlank( range ) )
            {
                const [start, end] = range.replace( "bytes=", _mt ).split( _hyphen ).map( asInt );
                return createReadStream( filePath, { start, end } );
            }

            return createReadStream( filePath );
        }

        /**
         * Removes the content stored at the specified key as well as any associated metadata.
         *
         * That is, deletes the specified file and its metadata.
         *
         * @param {string} pKey
         *
         * @returns {Promise<boolean>}
         */
        async delete( pKey )
        {
            const key = asString( pKey, true );

            const filePath = this.#resolvePath( key );
            const metaPath = this.#getMetadataPath( filePath );

            await asyncAttempt( async() => await fsAsync.unlink( filePath ).catch( () => {} ) );
            await asyncAttempt( async() => await fsAsync.unlink( metaPath ).catch( () => {} ) );

            const fileExists = await this.exists( key );

            if ( !fileExists )
            {
                attempt( () => this.dispatchEvent( new ModuleEvent( "delete",
                                                                    { detail: [key, fileExists] },
                                                                    { key, fileExists } ) ) );
            }

            return !fileExists;
        }

        /**
         * Removes one or more entries in the blob store.
         * That is, deletes the specified files and any associated metadata.
         *
         * @param {...string} pKeys
         *
         * @returns {Promise<{deleted: *[], failed: *[]}>}
         */
        async deleteMany( ...pKeys )
        {
            const keys = asArray( pKeys ?? [] );

            const deleted = [];
            const failed = [];

            for( const key of keys )
            {
                try
                {
                    await this.delete( key );
                    deleted.push( key );
                }
                catch( err )
                {
                    failed.push( { key, message: err.message } );
                }
            }

            attempt( () => this.dispatchEvent( new ModuleEvent( "delete",
                                                                { detail: { deleted, failed } },
                                                                { deleted, failed } ) ) );

            return { deleted, failed };
        }

        /**
         * Returns true if the specified key exists in the blob store (file system)
         *
         * @param {string} pKey
         *
         * @returns {Promise<boolean>}
         */
        async exists( pKey )
        {
            const key = asString( pKey, true );

            try
            {
                const filePath = this.#resolvePath( key );
                await fsAsync.access( filePath );
                return true;
            }
            catch
            {
                return false;
            }
        }

        /**
         * Returns any metadata stored with the content found at the specified key
         *
         * @param {string} pKey
         *
         * @returns {Promise<Object>}
         */
        async getMetadata( pKey )
        {
            const key = asString( pKey, true );

            const filePath = this.#resolvePath( key );

            const stats = await fsAsync.stat( filePath );

            let meta = { contentType: "application/octet-stream", customMetadata: {} };

            try
            {
                const data = await fsAsync.readFile( this.#getMetadataPath( filePath ), "utf-8" );
                meta = asObject( data );
            }
            catch
            {
                // Fallback if .meta.json file is missing
            }

            const obj =
                {
                    ...(asObject( meta )),
                    ...(asObject( meta?.customMetadata ?? {} )),
                    size: stats.size,
                    lastModified: stats.mtime,
                    contentType: readProperty( meta, "content_type", "mime_type" ) || "application/octet-stream",
                    etag: `"${stats.mtimeMs.toString( 16 )}-${stats.size.toString( 16 )}"`,
                    customMetadata: meta?.customMetadata ?? {}
                };

            return lock( obj );
        }

        /**
         * Returns an object containing a collection of files found under the specified prefix (path).
         *
         *
         * @param {string} pPrefix
         * @param {object} pOptions
         *
         * @returns {Promise<Object>}
         */
        async list( pPrefix = _mt, pOptions = {} )
        {
            const prefix = asString( pPrefix, true );

            const items = [];

            for await ( const item of this.listStream( prefix ) )
            {
                items.push( item );
            }

            const options = asObject( pOptions ?? {} );

            const limit = asInt( options.limit || items.length );
            const startIndex = options.cursor ? asInt( options.cursor ) : 0;
            const sliced = items.slice( startIndex, startIndex + limit );
            const nextIndex = startIndex + limit;

            const obj =
                {
                    items: sliced,
                    nextCursor: nextIndex < items.length ? asString( nextIndex ) : undefined,
                    isTruncated: nextIndex < items.length,
                    hasMore: function() { return nextIndex < items.length; },
                    limit,
                    startIndex,
                    nextIndex
                };

            return lock( obj );
        }

        /**
         * Asynchronously generates a stream
         * of file metadata objects
         * for files in a specified directory and its subdirectories.
         *
         * @param {string} [pPrefix=_mt] - The prefix or relative path inside the root folder from which to start listing files.
         *
         * @param {Object} [pOptions={}] - Additional options for the method (currently unused).
         *
         * @return {AsyncGenerator<Object>} An async iterable generator
         *                                  yielding file metadata objects.
         *
         *                                  Each object contains:
         *                                  - `key`: The relative path of the file.
         *                                  - `size`: The size of the file in bytes.
         *                                  - `lastModified`: The last modified date of the file.
         *                                  - `etag`: A unique identifier based on the file's modification time and size.
         */
        async* listStream( pPrefix = _mt, pOptions = {} )
        {
            const prefix = asString( pPrefix, true );

            const options = asObject( pOptions ?? {} );

            const targetDir = join( this.rootFolder, prefix );

            async function* walkDir( currentDir, rootFolder )
            {
                const entries = await asyncAttempt( async() => await fsAsync.readdir( currentDir, { withFileTypes: true } ) );

                for( const entry of entries )
                {
                    const fileName = asString( entry.name, true );

                    // omit metadata files
                    if ( fileName.endsWith( ".meta.json" ) )
                    {
                        continue;
                    }

                    const fullPath = join( currentDir, fileName );

                    if ( entry.isDirectory() )
                    {
                        yield* walkDir( fullPath, rootFolder );
                    }
                    else if ( entry.isFile() )
                    {
                        const relativeKey = relativePath( rootFolder, fullPath ).replace( /\\/g, "/" );

                        const stats = await fsAsync.stat( fullPath );

                        const obj =
                            {
                                fullPath,
                                key: relativeKey,
                                size: stats.size,
                                lastModified: stats.mtime,
                                etag: `"${stats.mtimeMs.toString( 16 )}-${stats.size.toString( 16 )}"`,
                            };

                        yield lock( obj );
                    }
                }
            }

            yield* walkDir( targetDir, this.rootFolder );
        }

        /**
         * Generates a presigned URL for accessing or interacting with a resource in the blob store.
         *
         * @param {string} pKey - The key identifying the resource in the blob store.
         * @param {string} [pOperation=BLOB_STORE_OPERATIONS.READ] - The operation to be performed (e.g., READ, WRITE, DELETE).
         * @param {Object} [pOptions={}] - Additional options for the presigned URL, such as expiration time.
         * @param {number} [pOptions.expiresInSeconds=3600] - The time (in seconds) until the URL expires.
         *
         * @return {Promise<string>} A promise that resolves to the presigned URL.
         */
        async getPresignedUrl( pKey, pOperation = BLOB_STORE_OPERATIONS.READ, pOptions = {} )
        {
            const key = asString( pKey, true );

            const options = asObject( pOptions ?? {} );

            // For local testing, returns a direct HTTP endpoint mock
            return `${this.baseUrl}/${key}?op=${operation}&expires=${options.expiresInSeconds || 3600}`;
        }


        /**
         * Copies the content found at the specified source key to a new path specified by the destination key.
         *
         * @param {string} pSourceKey
         * @param {string} pDestinationKey
         *
         * @returns {Promise<boolean>} true if the content is successfully copied
         */
        async copy( pSourceKey, pDestinationKey )
        {
            const sourceKey = asString( pSourceKey, true );
            const destinationKey = asString( pDestinationKey, true );

            if ( isBlank( sourceKey ) || isBlank( destinationKey ) )
            {
                throw new IllegalArgumentError( `Both a source path and destination path are required`, { detail: [sourceKey, destinationKey] }, sourceKey, destinationKey );
            }

            const srcPath = this.#resolvePath( sourceKey );
            const destPath = this.#resolvePath( destinationKey );

            if ( _lct( srcPath ) === _lct( destPath ) )
            {
                throw new IllegalArgumentError( `The source and destination paths cannot be the same`, { detail: [srcPath, destPath] }, srcPath, destPath, sourceKey, destinationKey );
            }

            await asyncAttempt( async() => await fsAsync.mkdir( getDirectoryName( destPath ), { recursive: true } ) );
            await asyncAttempt( async() => await fsAsync.copyFile( srcPath, destPath ) );

            const copied = await this.exists( destPath );

            if ( copied )
            {
                await asyncAttempt( async() => await fsAsync.copyFile( this.#getMetadataPath( srcPath ), this.#getMetadataPath( destPath ) ) );

                attempt( () => this.dispatchEvent( new ModuleEvent( "copy",
                                                                    { detail: [srcPath, destPath] },
                                                                    { sourceKey, destinationKey } ) ) );
            }

            return copied;
        }

        async move( pSourceKey, pDestinationKey )
        {
            const sourceKey = asString( pSourceKey, true );
            const destinationKey = asString( pDestinationKey, true );

            if ( isBlank( sourceKey ) || isBlank( destinationKey ) )
            {
                throw new IllegalArgumentError( `Both a source path and destination path are required`, { detail: [sourceKey, destinationKey] }, sourceKey, destinationKey );
            }

            const srcPath = this.#resolvePath( sourceKey );
            const destPath = this.#resolvePath( destinationKey );

            if ( _lct( srcPath ) === _lct( destPath ) )
            {
                throw new IllegalArgumentError( `The source and destination paths cannot be the same`, { detail: [srcPath, destPath] }, srcPath, destPath, sourceKey, destinationKey );
            }

            const copied = await asyncAttempt( async() => this.copy( sourceKey, destinationKey ) );

            if ( copied )
            {
                const deleted = await asyncAttempt( async() => await this.delete( sourceKey ) );

                if ( !deleted )
                {
                    attempt( () => this.dispatchEvent( new ModuleEvent( "error",
                                                                        { detail: new __Error( `Could not complete the move of ${srcPath} to ${destPath}; the source could not be removed` ) },
                                                                        { copied, deleted } ) ) );
                }

                return copied && deleted;
            }

            return false;
        }

        [Symbol.toStringTag]()
        {
            return `[object ${getClassName( this )}]`;
        }
    }


    /**
     * Factory for returning a BlobStorageClient
     * specific to a particular implementation
     *
     * @class
     * @factory
     */
    class BlobStoreClientFactory extends EventTarget
    {
        #classes = new Map();
        #instances = new Map();

        constructor()
        {
            // no-args/no-op
            super();
        }

        registerClass( pKey, pClass )
        {
            const key = asString( pKey, true );

            let klass = isClass( pClass ) ? pClass : isNonNullObject( pClass ) && pClass instanceof BlobStorageClient ? getClass( pClass ) : LocalDiskStorageClient;

            if ( isSubclassOf( klass, BlobStorageClient ) )
            {
                this.#classes.set( key, klass );

                attempt( () => this.dispatchEvent( new ModuleEvent( "registerClass", { detail: [key, klass] } ) ) );
            }
        }

        registerSingleton( pKey, pInstance )
        {
            const key = asString( pKey, true );

            if ( isClass( pInstance ) )
            {
                this.registerClass( key, pInstance );

                return;
            }

            const instance = asObject( pInstance );

            if ( isNonNullObject( instance ) && instance instanceof BlobStorageClient )
            {
                this.#instances.set( key, instance );

                attempt( () => this.dispatchEvent( new ModuleEvent( "registerSingleton", { detail: [key, instance] } ) ) );
            }
        }

        getClient( pKey, ...pArgs )
        {
            const key = asString( pKey, true );

            const args = asArray( pArgs ?? [] );

            let instance = null;

            if ( $ln( args ) > 0 )
            {
                instance = this.#instances.get( key );
            }

            if ( isNonNullObject( instance ) && instance instanceof BlobStorageClient )
            {
                return instance;
            }

            let klass = this.#classes.get( key );

            if ( !isNull( klass ) && isClass( klass ) )
            {
                instance = new klass( ...args );
            }

            if ( isNonNullObject( instance ) && instance instanceof BlobStorageClient )
            {
                this.registerSingleton( key, instance );

                return instance;
            }
        }

        getRegisteredClasses()
        {
            return this.#classes.entries();
        }

        getRegisteredSingletons()
        {
            return this.#instances.entries();
        }

        unregisterClass( pKey )
        {
            const key = asString( pKey, true );

            attempt( () => this.unregisterSingleton( key ) );

            const deleted = attempt( () => this.#classes.delete( key ) );

            if ( deleted )
            {
                attempt( () => this.dispatchEvent( new ModuleEvent( "unregisterClass", { detail: key }, { deleted } ) ) );
            }

            return deleted;
        }

        unregisterSingleton( pKey )
        {
            const key = asString( pKey, true );

            const deleted = attempt( () => this.#instances.delete( key ) );

            if ( deleted )
            {
                attempt( () => this.dispatchEvent( new ModuleEvent( "unregisterSingleton", { detail: key }, { deleted } ) ) );
            }

            return deleted;
        }

        clear()
        {
            attempt( () => this.#instances.clear() );
            attempt( () => this.#classes.clear() );

            attempt( () => this.dispatchEvent( new ModuleEvent( "clear" ) ) );
        }

        [Symbol.toStringTag]()
        {
            return `[object ${getClassName( this )}]`;
        }
    }

    const BLOB_STORE_CLIENT_KEYS =
        lock( {
                  FILE_SYSTEM: "FILE_SYSTEM",
                  AWS_S3: "S3",
                  AZURE: "AZURE",
                  GOOGLE_CLOUD: "GOOGLE_CLOUD",
                  GOOGLE_DRIVE: "GOOGLE_DRIVE",
                  SHAREPOINT: "SHAREPOINT"
              } );

    const BLOB_STORE_CLIENT_FACTORY = new BlobStoreClientFactory();

    BLOB_STORE_CLIENT_FACTORY.registerClass( BLOB_STORE_CLIENT_KEYS.FILE_SYSTEM, LocalDiskStorageClient );

    const mod =
        {
            BLOB_STORE_OPERATIONS,
            BLOB_STORE_CLIENT_KEYS,
            BLOB_STORE_CLIENT_FACTORY,
            classes:
                {
                    BlobStorageClient,
                    LocalDiskStorageClient,
                    BlobStoreClientFactory
                },
            EVENTS: ["clear", "delete", "registerClass", "unregisterClass", "registerSingleton", "unregisterSingleton", "upload", "copy"],
            BlobStorageClient,
            LocalDiskStorageClient,
            BlobStoreClientFactory
        };

    if ( _ud !== typeof module )
    {
        module.exports = lock( mod );
    }

    attempt( () => $scope()[INTERNAL_NAME] = lock( mod ) );

    return lock( mod );

}());
