/**
 * This is the abstract/generic interface for a "connection"
 * to a blob storage service, such as Amazon Web Services S3
 * Azure's "blob store", or a local (or network-mapped) file system.
 *
 * @module
 */

const fsAsync = require( "fs/promises" );

// TODO: make platform-agnostic, not tied to node,js
const { createReadStream, createWriteStream } = require( "node:fs" );
const { Readable, pipeline } = require( "node:stream" );
const { promisify } = require( "node:util" );

const core = require( "@toolbocks/core" );
const bufferUtils = require( "@toolbocks/buffer" );
const fileUtils = require( "@toolbocks/files" );
const jsonUtils = require( "@toolbocks/json" );

const { moduleUtils, constants, typeUtils, stringUtils, arrayUtils } = core;

const { _ud, _mt = "", _hyphen, _pathSep = "/", _fun, $scope } = constants;

(function exposeModule()
{
    /**
     * Define a string key which is unlikely to collide with other libraries or properties.
     * We use this to store the module generated by this function in global scope.
     * We can avoid re-executing the rest of this function if the module is already defined.
     */
    const INTERNAL_NAME = "__BOCK__STORAGE_UTILS_BASE__";

    /**
     * Checks to see if this module is already defines and available in the global scope
     * Returns the existing module instead of recreating it, if it is already present.
     */
    if ( $scope() && (null != $scope()[INTERNAL_NAME]) )
    {
        return $scope()[INTERNAL_NAME];
    }

    const
        {
            ToolBocksModule,
            ModuleEvent,
            __Error,
            IllegalArgumentError,
            NotImplementedError,
            hasProperty,
            readProperty,
            attempt,
            attemptSilent,
            asyncAttempt,
            lock,
            $ln
        } = moduleUtils;

    const
        {
            isNull,
            isNonNullObject,
            isFunction,
            isString,
            isArray,
            isTypedArray,
            isClass,
            getClass,
            getClassName,
            isSubclassOf
        } = typeUtils;

    const { asString, asInt, _lct, isBlank, toBool } = stringUtils;

    const { asArray } = arrayUtils;

    const { join, normalize, resolvePath, relativePath, getDirectoryName, getTempDirectory } = fileUtils;

    const { asObject, asJson, parseJson } = jsonUtils;

    const BLOB_STORE_OPERATIONS =
        lock( {
                  READ: "read",
                  WRITE: "write"
              } );

    /**
     * Abstract base class for Blob Store Clients,
     * such as AWS S3, Azure Client, or the File System.
     *
     * @abstract
     * @class
     *
     */
    class BlobStorageClient extends EventTarget
    {
        constructor()
        {
            super();

            // prevent direct instantiation
            if ( new.target === BlobStorageClient )
            {
                throw new __Error( "Cannot instantiate abstract class BlobStorageClient directly. BlobStorageClient is intended to be subclassed" );
            }
        }

        /**
         * Initialize any underlying resources,
         * such as authentication headers.
         *
         * @param {...*} pArgs any arguments required to initialize a specific instance
         *
         * @returns {Promise<BlobStorageClient>}
         */
        async init( ...pArgs )
        {
            return this;
        }

        /**
         * Performs any necessary disposal of underlying resources.
         *
         * @param {...*} pArgs any arguments necessary to gracefully dispose this instance.
         *
         * @returns {Promise<BlobStorageClient>}
         */
        async dispose( ...pArgs )
        {
            return this;
        }

        /**
         * Stores the provided data under the specified key.
         *
         * For subclasses that are constructed with a container, bucket, or root folder,
         * this key should be relative to that path.
         *
         * @param {string} pKey the key,
         *                      relative to the root container, bucket, folder, site, or document library
         *                      under which to store the specified content.
         *
         * @param {Buffer|TypedArray|String} pData the content to store under the specified key
         *
         * @param {Object} [pOptions={}] (optional) an object specifying the encoding to use for string data
         *                               and/or metadata to store with the content.
         *
         * @returns {Promise<Object>} an object with the resolve path, key, ETag, and other storage-specific information identifying the persisted content
         */
        async upload( pKey, pData, pOptions = {} )
        {
            throw new NotImplementedError( "Method 'upload()' must be implemented." );
        }

        /**
         * Returns a ReadStream of the bytes requested.
         *
         * @param {string} pKey path relative to the root
         *
         * @param {object} [pOptions={}] (optional) an object specifying the range of bytes to return
         *                               example: {start: 0, end: 4099}
         *
         * @returns {Promise<ReadStream>} a stream to consume
         */
        async download( pKey, pOptions = {} )
        {
            throw new NotImplementedError( "Method 'download()' must be implemented." );
        }

        /**
         * Removes the content stored at the specified key as well as any associated metadata.
         *
         * @param {string} pKey the path, relative to the root, to the item to delete
         *
         * @returns {Promise<boolean>} true if the item and its metadata are successfully removed
         */
        async delete( pKey )
        {
            throw new NotImplementedError( "Method 'delete()' must be implemented." );
        }

        /**
         * Removes one or more items and associated metadata in the blob store.
         *
         * @param {...string} pKeys one or more paths, relative to the root, indicating which items to remove
         *
         * @returns {Promise<{deleted: *[], failed: *[]}>} an object with an array of the items successfully deleted
         *                                                 and an array of the items that could not be removed.
         */
        async deleteMany( ...pKeys )
        {
            throw new NotImplementedError( "Method 'deleteMany()' must be implemented." );
        }

        /**
         * Returns true if the specified key exists in the blob store (file system)
         *
         * @param {string} pKey path, or key, relative to the root, for which to search the store
         *
         * @returns {Promise<boolean>} true if the blob store contains an item at the indicated path/key
         */
        async exists( pKey )
        {
            throw new NotImplementedError( "Method 'exists()' must be implemented." );
        }

        /**
         * Returns any metadata stored with the content found at the specified key
         *
         * @param {string} pKey path, or key, relative to the root for which metadata will be returned
         *
         * @returns {Promise<Object>} an object with available metadata for the item stored under the specified key
         */
        async getMetadata( pKey )
        {
            throw new NotImplementedError( "Method 'getMetadata()' must be implemented." );
        }

        /**
         * Returns an object containing a collection of metadata
         * for items found under the specified prefix (path).
         *
         * @param {string} pPrefix
         * @param {Object} pOptions
         *
         * @returns {Promise<Object>}
         */
        async list( pPrefix = _mt, pOptions = {} )
        {
            throw new NotImplementedError( "Method 'list()' must be implemented." );
        }

        /**
         * Async generator that yields objects
         * containing metadata for items found under the specified prefix (path)
         * one by one across page boundaries.
         *
         * @param {string} pPrefix the path, relative to the root container, bucket, folder, site, or document library
         *                         for which to yield metadata objects for each item contained therein
         *
         * @param {Object} [pOptions={}] an object specifying storage-specific parameters
         *
         * @returns {AsyncGenerator<Object>}
         */
        async* listStream( pPrefix = "", pOptions = {} )
        {
            throw new NotImplementedError( "Method 'listStream()' must be implemented." );
        }

        /**
         * Returns a URI that can be used by anyone to download the item stored under the specified key.
         * This URI may be configured to expire after some period of time.
         *
         * (NOTE: This method may not be applicable to all subclasses, for example, when storing to a local file system)
         *
         * @param {String} pKey
         * @param {String} pOperation one of either "read" or "write" (which implies "read")
         *                            specifying what operation(s) the URI performs or allows.
         *
         * @param {Object} [pOptions={}] - Additional options for the presigned URL, such as the expiration time
         * @param {number} [pOptions.expiresInSeconds=3600] - The time (in seconds) until the URI expires
         *
         * @returns {Promise<String>}
         */
        async getPresignedUrl( pKey, pOperation = BLOB_STORE_OPERATIONS.READ, pOptions = {} )
        {
            throw new NotImplementedError( "Method 'getPresignedUrl()' must be implemented." );
        }

        /**
         * Copies the content found at the specified source key
         * to a new path specified by the destination key.
         *
         * @param {string} pSourceKey
         * @param {string} pDestinationKey
         *
         * @param {boolean} [pOverwrite=true] specifies whether to replace
         *                                    any content that might already exist
         *                                    at the specified destination.
         *                                    <b>Defaults to true</b>
         *
         * @returns {Promise<boolean>} true if the content is successfully copied
         */
        async copy( pSourceKey, pDestinationKey, pOverwrite = true )
        {
            throw new NotImplementedError( "Method 'copy()' must be implemented." );
        }

        /**
         * Returns a string used when JavaScript coerces this object to a string.
         *
         * @returns {string} a string of the form, "[object ClassName]"
         */
        [Symbol.toStringTag]()
        {
            return `[object ${getClassName( this )}]`;
        }
    }


    /**
     * Adapted version of the pipeline function for use in an asynchronous context
     */
    const streamPipeline = promisify( pipeline );

    /**
     * A client for storing and managing file-based blobs in the local filesystem.
     * Extends the BlobStorageClient to provide local disk storage functionality.
     *
     * @class
     *
     * @see BlobStorageClient
     */
    class LocalDiskStorageClient extends BlobStorageClient
    {
        /**
         * Constructs an instance of LocalDiskStorageClient
         * and initializes it with the provided options.
         *
         * @param {Object} [pOptions={}] - The options used to configure the instance.
         * @param {string} [pOptions.rootFolder] - The root folder path for the instance. Defaults to a temporary directory.
         * @param {string} [pOptions.baseUrl] - The base URL for the instance. Defaults to a file URL based on the root folder.
         *
         * @constructor
         */
        constructor( pOptions = {} )
        {
            super( pOptions );

            const options = asObject( pOptions ?? {} );

            const root = asString( options.rootFolder || getTempDirectory(), true ) || getTempDirectory();

            this.rootFolder = resolvePath( root );

            this.baseUrl = options.baseUrl || asString( `file:///${this.rootFolder}/` ).replaceAll( /\/{4}/g, "///" );
        }

        /**
         * Returns the full path to the desired content,
         * safely preventing navigation outside the root folder.
         *
         * @throws IllegalArgumentError if the resolved path does not start with the root folder
         *
         * @param {string} pKey path/name to content
         *
         * @returns {string} the full path to the desired content
         */
        #resolvePath( pKey )
        {
            const key = asString( pKey, true );

            const safeKey = normalize( key ).replace( /^(\.\.[\/\\])+/, _mt );
            const fullPath = resolvePath( join( this.rootFolder, safeKey ) );

            if ( fullPath !== this.rootFolder && !fullPath.startsWith( this.rootFolder + _pathSep ) )
            {
                throw new IllegalArgumentError( "Directory traversal out of root folder is forbidden.", { detail: key }, key );
            }

            return fullPath;
        }

        /**
         * Returns the file path to the metadata for the file.
         * N.B. May not exist!
         *
         * @param pFilePath
         *
         * @returns {string}
         *
         * @private
         */
        #getMetadataPath( pFilePath )
        {
            const filePath = asString( pFilePath, true );
            return `${filePath}.meta.json`;
        }

        /**
         * Stores the provided data under the key specified.
         * That is, saves the bytes or string as a file.
         *
         * @param {string} pKey a path or name relative to the root folder at which to store the specified data
         *
         * @param {Buffer|TypedArray|String} pData the content to store
         *
         * @param {Object} [pOptions={}] (optional) an object specifying the encoding to use for string data
         *                               and/or metadata to store with the content.
         *
         * @returns {Promise<Object>} an object with the resolved key, filePath, ETag, and url of the stored data.
         */
        async upload( pKey, pData, pOptions = {} )
        {
            const key = asString( pKey, true );

            const options = asObject( pOptions ?? {} );

            const metadata = { ...(asObject( options.metadata ?? {} )) };

            metadata.contentType = readProperty( options, "content_type", "mime_type" ) ||
                                   readProperty( metadata, "content_type", "mime_type" ) ||
                                   "application/octet-stream";

            const encoding = asString( options.encoding || metadata.encoding || "utf-8", true ) || "utf-8";

            const filePath = this.#resolvePath( key );

            await fsAsync.mkdir( getDirectoryName( filePath ), { recursive: true } );

            if ( isTypedArray( pData ) || Buffer.isBuffer( pData ) )
            {
                await fsAsync.writeFile( filePath, (Buffer.isBuffer( pData ) ? pData : Buffer.from( pData?.buffer ?? pData )) );
            }
            else if ( isString( pData ) )
            {
                await fsAsync.writeFile( filePath, asString( pData ), encoding );
            }
            else if ( pData instanceof Readable || _fun === typeof pData[Symbol.asyncIterator] )
            {
                const writeStream = createWriteStream( filePath );

                await asyncAttempt( async() => await streamPipeline( pData, writeStream ) );

                // pipeline handles closing the stream
                // await asyncAttempt( async() => writeStream.close() );
            }
            else
            {
                throw new IllegalArgumentError( "Unsupported data format for LocalDiskStorageClient upload.",
                                                {
                                                    detail: pData,
                                                    type: typeof pData
                                                }, pData );
            }

            await asyncAttempt( async() => await fsAsync.writeFile( this.#getMetadataPath( filePath ), asJson( metadata ?? options ) ) );

            const stats = await fsAsync.stat( filePath );

            if ( isNonNullObject( stats ) )
            {
                const obj =
                    {
                        key,
                        filePath,
                        etag: `"${stats.mtimeMs.toString( 16 )}-${stats.size.toString( 16 )}"`,
                        url: `${this.baseUrl}/${key}`,
                    };

                attempt( () => this.dispatchEvent( new ModuleEvent( "upload", { detail: obj }, { ...obj } ) ) );

                return lock( obj );
            }

            throw new __Error( `Failed to persist ${filePath}` );
        }

        /**
         * Returns a ReadStream of the bytes requested.
         *
         * @param {string} pKey file path or name, relative to the root folder
         *
         * @param {object} [pOptions={}] (optional) an object specifying the range of bytes to return
         *                               example: {start: 0, end: 4099}
         *
         * @returns {Promise<ReadStream>} a stream to consume
         */
        async download( pKey, pOptions = {} )
        {
            const key = asString( pKey, true );

            const options = asObject( pOptions ?? {} );

            const filePath = this.#resolvePath( key );

            const range = asString( readProperty( options, "range" ), true );

            if ( range && !isBlank( range ) )
            {
                const [start, end] = range.replace( "bytes=", _mt ).split( _hyphen ).map( asInt );
                return createReadStream( filePath, { start, end } );
            }

            return createReadStream( filePath );
        }

        /**
         * Removes the content stored at the specified key as well as any associated metadata.
         *
         * That is, deletes the specified file and its metadata.
         *
         * @param {string} pKey
         *
         * @returns {Promise<boolean>}
         */
        async delete( pKey )
        {
            const key = asString( pKey, true );

            const filePath = this.#resolvePath( key );
            const metaPath = this.#getMetadataPath( filePath );

            await asyncAttempt( async() => await fsAsync.unlink( filePath ).catch( () => {} ) );
            await asyncAttempt( async() => await fsAsync.unlink( metaPath ).catch( () => {} ) );

            const fileExists = await this.exists( key );

            if ( !fileExists )
            {
                attempt( () => this.dispatchEvent( new ModuleEvent( "delete",
                                                                    { detail: [key, fileExists] },
                                                                    { key, fileExists } ) ) );
            }

            return !fileExists;
        }

        /**
         * Removes one or more entries in the blob store.
         * That is, deletes the specified files and any associated metadata.
         *
         * @param {...string} pKeys
         *
         * @returns {Promise<{deleted: *[], failed: *[]}>}
         */
        async deleteMany( ...pKeys )
        {
            const keys = asArray( pKeys ?? [] );

            const deleted = [];
            const failed = [];

            for( const key of keys )
            {
                try
                {
                    await this.delete( key );
                    deleted.push( key );
                }
                catch( err )
                {
                    failed.push( { key, message: err.message } );
                }
            }

            attempt( () => this.dispatchEvent( new ModuleEvent( "delete",
                                                                { detail: { deleted, failed } },
                                                                { deleted, failed } ) ) );

            return { deleted, failed };
        }

        /**
         * Returns true if the specified key exists in the blob store (file system)
         *
         * @param {string} pKey
         *
         * @returns {Promise<boolean>}
         */
        async exists( pKey )
        {
            const key = asString( pKey, true );

            try
            {
                const filePath = this.#resolvePath( key );
                await fsAsync.access( filePath );
                return true;
            }
            catch
            {
                return false;
            }
        }

        /**
         * Returns any metadata stored with the content found at the specified key
         *
         * @param {string} pKey
         *
         * @returns {Promise<Object>}
         */
        async getMetadata( pKey )
        {
            const key = asString( pKey, true );

            const filePath = this.#resolvePath( key );

            const stats = await fsAsync.stat( filePath );

            let meta = { contentType: "application/octet-stream", customMetadata: {} };

            try
            {
                const data = await fsAsync.readFile( this.#getMetadataPath( filePath ), "utf-8" );
                meta = asObject( data );
            }
            catch
            {
                // Fallback if .meta.json file is missing
            }

            const obj =
                {
                    ...(asObject( meta )),
                    ...(asObject( meta?.customMetadata ?? {} )),
                    size: stats.size,
                    lastModified: stats.mtime,
                    contentType: readProperty( meta, "content_type", "mime_type" ) || "application/octet-stream",
                    etag: `"${stats.mtimeMs.toString( 16 )}-${stats.size.toString( 16 )}"`,
                    customMetadata: meta?.customMetadata ?? {}
                };

            return lock( obj );
        }

        /**
         * Returns an object containing a collection of metadata
         * for files found under the specified prefix (path).
         *
         *
         * @param {string} pPrefix
         * @param {object} pOptions
         *
         * @returns {Promise<Object>}
         */
        async list( pPrefix = _mt, pOptions = {} )
        {
            const prefix = asString( pPrefix, true );

            const items = [];

            for await ( const item of this.listStream( prefix ) )
            {
                items.push( item );
            }

            const options = asObject( pOptions ?? {} );

            const limit = asInt( options.limit || items.length );
            const startIndex = options.cursor ? asInt( options.cursor ) : 0;
            const sliced = items.slice( startIndex, startIndex + limit );
            const nextIndex = startIndex + limit;

            const obj =
                {
                    items: sliced,
                    nextCursor: nextIndex < items.length ? asString( nextIndex ) : undefined,
                    isTruncated: nextIndex < items.length,
                    hasMore: function() { return nextIndex < items.length; },
                    limit,
                    startIndex,
                    nextIndex
                };

            return lock( obj );
        }

        /**
         * Asynchronously generates a stream
         * of file metadata objects
         * for files in a specified directory and its subdirectories.
         *
         * @param {string} [pPrefix=_mt] - The prefix or relative path inside the root folder from which to start listing files.
         *
         * @param {Object} [pOptions={}] - Additional options for the method (currently unused).
         *
         * @return {AsyncGenerator<Object>} An async iterable generator
         *                                  yielding file metadata objects.
         *
         *                                  Each object contains:
         *                                  - `key`: The relative path of the file.
         *                                  - `size`: The size of the file in bytes.
         *                                  - `lastModified`: The last modified date of the file.
         *                                  - `etag`: A unique identifier based on the file's modification time and size.
         */
        async* listStream( pPrefix = _mt, pOptions = {} )
        {
            const prefix = asString( pPrefix, true );

            const options = asObject( pOptions ?? {} );

            const recursive = toBool( readProperty( options, "recursive", "include_sub_folders" ) );

            const targetDir = this.#resolvePath( prefix );

            async function* walkDir( currentDir, rootFolder, pRecursive = recursive )
            {
                const entries = await asyncAttempt( async() => await fsAsync.readdir( currentDir, { withFileTypes: true } ) );

                if ( entries )
                {
                    for( const entry of entries )
                    {
                        const fileName = asString( entry.name, true );

                        // omit metadata files
                        if ( fileName.endsWith( ".meta.json" ) )
                        {
                            continue;
                        }

                        const fullPath = join( currentDir, fileName );

                        if ( entry.isDirectory() )
                        {
                            if ( toBool( pRecursive ) )
                            {
                                yield* walkDir( fullPath, rootFolder, pRecursive );
                            }
                        }
                        else if ( entry.isFile() )
                        {
                            const relativeKey = relativePath( rootFolder, fullPath ).replace( /\\/g, "/" );

                            const stats = await asyncAttempt( async() => await fsAsync.stat( fullPath ) );

                            const obj =
                                {
                                    fullPath,
                                    key: relativeKey,
                                    size: asInt( stats?.size ),
                                    lastModified: stats?.mtime || Date.now(),
                                    etag: isNonNullObject( stats ) ? `"${stats.mtimeMs.toString( 16 )}-${stats.size.toString( 16 )}"` : _mt,
                                };

                            yield lock( obj );
                        }
                    }
                }
            }

            yield* walkDir( targetDir, this.rootFolder, recursive );
        }

        /**
         * Generates a presigned URL for accessing or interacting with a resource in the blob store.
         *
         * @param {string} pKey - The key identifying the resource in the blob store.
         * @param {string} [pOperation=BLOB_STORE_OPERATIONS.READ] - The operation to be performed (e.g., READ, WRITE, DELETE).
         * @param {Object} [pOptions={}] - Additional options for the presigned URL, such as expiration time.
         * @param {number} [pOptions.expiresInSeconds=3600] - The time (in seconds) until the URL expires.
         *
         * @return {Promise<string>} A promise that resolves to the presigned URL.
         */
        async getPresignedUrl( pKey, pOperation = BLOB_STORE_OPERATIONS.READ, pOptions = {} )
        {
            const key = asString( pKey, true );

            const options = asObject( pOptions ?? {} );

            const operation = pOperation || readProperty( options, "operation", "op" ) || BLOB_STORE_OPERATIONS.READ;

            // For local testing, returns a direct HTTP endpoint mock
            return `${this.baseUrl}/${key}?op=${operation}&expires=${options.expiresInSeconds || 3600}`;
        }

        /**
         * Copies the content found at the specified source key to a new path specified by the destination key.
         *
         * @param {string} pSourceKey
         * @param {string} pDestinationKey
         *
         * @param {boolean} pOverwrite specifies whether to overwrite an existing file
         *
         * @returns {Promise<boolean>} true if the content is successfully copied
         */
        async copy( pSourceKey, pDestinationKey, pOverwrite = true )
        {
            const sourceKey = asString( pSourceKey, true );
            const destinationKey = asString( pDestinationKey, true );

            if ( isBlank( sourceKey ) || isBlank( destinationKey ) )
            {
                throw new IllegalArgumentError( `Both a source path and destination path are required`, { detail: [sourceKey, destinationKey] }, sourceKey, destinationKey );
            }

            const srcPath = this.#resolvePath( sourceKey );
            const destPath = this.#resolvePath( destinationKey );

            if ( _lct( srcPath ) === _lct( destPath ) )
            {
                throw new IllegalArgumentError( `The source and destination paths cannot be the same`, { detail: [srcPath, destPath] }, srcPath, destPath, sourceKey, destinationKey );
            }

            const overwrite = toBool( pOverwrite );

            await asyncAttempt( async() => await fsAsync.mkdir( getDirectoryName( destPath ), { recursive: true } ) );

            if ( !overwrite )
            {
                const alreadyExists = await this.exists( destPath );
                if ( alreadyExists )
                {
                    return false;
                }
            }

            try
            {
                await fsAsync.rename( srcPath, destPath );
                return await this.exists( destPath );
            }
            catch( ex )
            {
                attempt( () => this.dispatchEvent( new ModuleEvent( "error",
                                                                    { detail: new __Error( `Could not rename ${srcPath} to ${destPath}` ) },
                                                                    { sourceKey, destinationKey } ) ) );

            }

            await asyncAttempt( async() => await fsAsync.copyFile( srcPath, destPath ) );

            const copied = await this.exists( destPath );

            if ( copied )
            {
                await asyncAttempt( async() => await fsAsync.copyFile( this.#getMetadataPath( srcPath ), this.#getMetadataPath( destPath ) ) );

                attempt( () => this.dispatchEvent( new ModuleEvent( "copy",
                                                                    { detail: [srcPath, destPath] },
                                                                    { sourceKey, destinationKey } ) ) );
            }

            return copied;
        }

        /**
         * Moves an item to a new path/key within the same container, document library, bucket, or other root.
         * Returns true if the item is successfully moved.
         *
         * @param {String} pSourceKey
         * @param {String} pDestinationKey
         *
         * @returns {Promise<boolean>} true if the item was successfully moved
         */
        async move( pSourceKey, pDestinationKey )
        {
            const sourceKey = asString( pSourceKey, true );
            const destinationKey = asString( pDestinationKey, true );

            if ( isBlank( sourceKey ) || isBlank( destinationKey ) )
            {
                throw new IllegalArgumentError( `Both a source path and destination path are required`, { detail: [sourceKey, destinationKey] }, sourceKey, destinationKey );
            }

            const srcPath = this.#resolvePath( sourceKey );
            const destPath = this.#resolvePath( destinationKey );

            if ( _lct( srcPath ) === _lct( destPath ) )
            {
                throw new IllegalArgumentError( `The source and destination paths cannot be the same`, { detail: [srcPath, destPath] }, srcPath, destPath, sourceKey, destinationKey );
            }

            const copied = await asyncAttempt( async() => this.copy( sourceKey, destinationKey ) );

            if ( copied )
            {
                const deleted = await asyncAttempt( async() => await this.delete( sourceKey ) );

                if ( !deleted )
                {
                    attempt( () => this.dispatchEvent( new ModuleEvent( "error",
                                                                        { detail: new __Error( `Could not complete the move of ${srcPath} to ${destPath}; the source could not be removed` ) },
                                                                        { copied, deleted } ) ) );
                }

                return copied && deleted;
            }

            return false;
        }

        [Symbol.toStringTag]()
        {
            return `[object ${getClassName( this )}]`;
        }
    }


    /**
     * Factory for returning a BlobStorageClient
     * specific to a particular implementation
     *
     * @class
     * @factory
     */
    class BlobStoreClientFactory extends EventTarget
    {
        #classes = new Map();
        #instances = new Map();

        /**
         * Constructs an instance of the class.
         * This is a no-argument constructor that initializes the instance
         * without additional setup or input parameters.
         *
         * @return {Object} A new instance of the class.
         */
        constructor()
        {
            // no-args/no-op
            super();
        }

        /**
         * Associates a subclass of BlobStorageClient with a key.
         *
         * @param {String} pKey the key to use to retrieve the specified class
         *
         * @param {Function|Object} pClass a JavaScript class (or function that supports the "new" operator)
         *                                 or an instance of the class to associate with the specified key
         *
         * @returns {void} does not return a value
         *
         * @emits "registerClass"
         */
        registerClass( pKey, pClass )
        {
            const key = asString( pKey, true );

            let klass = isClass( pClass ) ? pClass : isNonNullObject( pClass ) && pClass instanceof BlobStorageClient ? getClass( pClass ) : LocalDiskStorageClient;

            if ( isSubclassOf( klass, BlobStorageClient ) )
            {
                this.#classes.set( key, klass );

                attempt( () => this.dispatchEvent( new ModuleEvent( "registerClass", { detail: [key, klass] } ) ) );
            }
        }

        /**
         * Associates an instance of a subclass of BlobStorageClient with a key.
         *
         * @param {String} pKey the key to use to retrieve the specified class
         *
         * @param {BlobStorageClient} pInstance  an instance of a subclass of BlobStorageClient to associate with the specified key
         *
         * @returns {void} does not return a value
         *
         * @emits "registerSingleton"
         */
        registerSingleton( pKey, pInstance )
        {
            const key = asString( pKey, true );

            if ( isClass( pInstance ) )
            {
                this.registerClass( key, pInstance );

                return;
            }

            const instance = asObject( pInstance );

            if ( isNonNullObject( instance ) && instance instanceof BlobStorageClient )
            {
                this.#instances.set( key, instance );

                attempt( () => this.dispatchEvent( new ModuleEvent( "registerSingleton", { detail: [key, instance] } ) ) );
            }
        }

        /**
         * Returns an instance of BlobStorageClient according to the key provided.
         * If no subclass of BlobStorageClient exists for the specified key, throws an IllegalArgumentException
         *
         * @param {String} pKey the string used to identify a storage-system-specific subclass of BlobStorageClient
         *
         * @param {...*} [pArgs] any arguments to pass to the subclass constructor
         *                       NOTE: if no arguments are specified,
         *                             this method <i>may</i> return an existing instance
         *                             which may also be in use by other consumers.
         *
         *
         * @returns {BlobStorageClient}
         *
         * @throws IllegalArgumentError if no subclass is registered/exists for the specified key
         */
        getClient( pKey, ...pArgs )
        {
            const key = asString( pKey, true );

            if ( isBlank( key ) )
            {
                throw new IllegalArgumentError( `A valid key is required`, { detail: pKey }, pKey );
            }

            const args = asArray( pArgs ?? [] );

            let instance = null;

            if ( $ln( args ) <= 0 )
            {
                instance = this.#instances.get( key );
            }

            if ( isNonNullObject( instance ) && instance instanceof BlobStorageClient )
            {
                return instance;
            }

            let klass = this.#classes.get( key );

            if ( !isNull( klass ) && isClass( klass ) )
            {
                instance = new klass( ...args );
            }

            if ( isNonNullObject( instance ) && instance instanceof BlobStorageClient )
            {
                if ( $ln( args ) <= 0 )
                {
                    this.registerSingleton( key, instance );
                }

                return instance;
            }

            throw new IllegalArgumentError( `No class registered for key, ${key}`, { detail: pKey }, pKey );
        }

        /**
         * Returns an iterator of all registered keys and their associated classes.
         *
         * @return {Iterator<[String, Function]>} An iterator containing the entries of registered classes,
         * where each entry is a key-value pair of the string key and the associated class/function.
         */
        getRegisteredClasses()
        {
            return this.#classes.entries();
        }

        /**
         * Retrieves an iterator of any registered singletons.
         *
         * The method returns an iterator over the key-value pairs where the key
         * represents the identifier of the singleton and the value is the corresponding
         * singleton instance.
         *
         * @return {Iterator<[String, BlobStorageClient]>} An iterator containing entries of registered singletons.
         */
        getRegisteredSingletons()
        {
            return this.#instances.entries();
        }

        /**
         * Removes the class associated with the specified key
         *
         * @param {String} pKey
         *
         * @returns {boolean} true if the class was removed
         *
         * @emits "unregisterClass"
         */
        unregisterClass( pKey )
        {
            const key = asString( pKey, true );

            attempt( () => this.unregisterSingleton( key ) );

            const deleted = attempt( () => this.#classes.delete( key ) );

            if ( deleted )
            {
                attempt( () => this.dispatchEvent( new ModuleEvent( "unregisterClass", { detail: key }, { deleted } ) ) );
            }

            return deleted;
        }

        /**
         * Removes the instance associated with the specified key
         *
         * @param {String} pKey
         *
         * @returns {boolean} true if the instance was removed
         *
         * @emits "unregisterSingleton"
         */
        unregisterSingleton( pKey )
        {
            const key = asString( pKey, true );

            const deleted = attempt( () => this.#instances.delete( key ) );

            if ( deleted )
            {
                attempt( () => this.dispatchEvent( new ModuleEvent( "unregisterSingleton", { detail: key }, { deleted } ) ) );
            }

            return deleted;
        }

        /**
         * Clears all stored instances and classes and dispatches a "clear" event.
         *
         * @return {void} This method does not return a value.
         *
         * @emits "clear"
         */
        clear()
        {
            attempt( () => this.#instances.clear() );
            attempt( () => this.#classes.clear() );

            attempt( () => this.dispatchEvent( new ModuleEvent( "clear" ) ) );
        }

        [Symbol.toStringTag]()
        {
            return `[object ${getClassName( this )}]`;
        }
    }

    /**
     * An object representing the supported keys for various blob storage clients.
     * This variable provides a centralized list of identifiers for different
     * storage providers that can be used to configure or interact with specific
     * blob storage systems.
     *
     * Available keys:
     * - FILE_SYSTEM: Represents a local file system storage.
     * - AWS_S3: Represents Amazon Web Services S3 storage.
     * - AZURE: Represents Microsoft Azure Blob storage.
     * - GOOGLE_CLOUD: Represents Google Cloud Storage.
     * - GOOGLE_DRIVE: Represents Google Drive storage.
     * - SHAREPOINT: Represents Microsoft SharePoint storage.
     */
    const BLOB_STORE_CLIENT_KEYS =
        lock( {
                  FILE_SYSTEM: "FILE_SYSTEM",
                  AWS_S3: "S3",
                  AZURE: "AZURE",
                  GOOGLE_CLOUD: "GOOGLE_CLOUD",
                  GOOGLE_DRIVE: "GOOGLE_DRIVE",
                  SHAREPOINT: "SHAREPOINT"
              } );

    /**
     * The singleton instance of the BlobStoreClientFactory
     * @type {BlobStoreClientFactory}
     */
    const BLOB_STORE_CLIENT_FACTORY = new BlobStoreClientFactory();

    // register the LocalDiskStorageClient
    BLOB_STORE_CLIENT_FACTORY.registerClass( BLOB_STORE_CLIENT_KEYS.FILE_SYSTEM, LocalDiskStorageClient );

    /*
     * Applications are responsible for registering any other subclasses
     */

    /**
     * The module to be returned when this function executes.
     * @type {{BLOB_STORE_OPERATIONS: *, BLOB_STORE_CLIENT_KEYS: *, BLOB_STORE_CLIENT_FACTORY: BlobStoreClientFactory, classes: {BlobStorageClient: BlobStorageClient, LocalDiskStorageClient: LocalDiskStorageClient, BlobStoreClientFactory: BlobStoreClientFactory}, EVENTS: string[], BlobStorageClient: BlobStorageClient, LocalDiskStorageClient: LocalDiskStorageClient, BlobStoreClientFactory: BlobStoreClientFactory}}
     */
    const mod =
        {
            BLOB_STORE_OPERATIONS,
            BLOB_STORE_CLIENT_KEYS,
            BLOB_STORE_CLIENT_FACTORY,
            classes:
                {
                    BlobStorageClient,
                    LocalDiskStorageClient
                },
            EVENTS: ["clear", "delete", "registerClass", "unregisterClass", "registerSingleton", "unregisterSingleton", "upload", "copy"],
            BlobStorageClient,
            LocalDiskStorageClient
        };

    if ( _ud !== typeof module )
    {
        module.exports = lock( mod );
    }

    attempt( () => $scope()[INTERNAL_NAME] = lock( mod ) );

    return lock( mod );

}());
